### ISSUE TITLE
Establish Google Analytics tracking

### ISSUE THREAD

**Issue by james-minton** [Hyperobjekt/spi-map#27]
- [ ] Establish basic GA tracking in app
- [ ] Create custom events in GTM and on front end for
  - [ ] which places are clicked
  - [ ] which metrics are selected
  - [ ] whether the scorecard view was triggered

JM to establish GA/GTM setup
Developer to implement on front end
